apiVersion: v1
kind: Service
metadata:
  name: captureorderfd0
  labels:
    app: captureorderfd0
  namespace: fd
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    run: captureorderfd0
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: captureorderfd0
  namespace: fd
spec:
  replicas: 3
  template:
    metadata:
      labels:
        run: captureorderfd0
        app: captureorderfd0
        namespace: fd
    spec:
      containers:
      - name: captureorderfd
        image: 
        env:
        - name: DATABASE
          value: ""
        - name: PASSWORD
          value: ""
        - name: INSIGHTSKEY
          value: ""
        - name: SOURCE
          value: ""
        - name: EVENTURL
          value: ""
        - name: EVENTPOLICYNAME
          value: ""
        - name: EVENTPOLICYKEY
          value: ""
        - name: PARTITIONKEY
          value: ""
        ports:
          - containerPort: 8080
      imagePullSecrets:
        - name: cadcontainerregistry
